name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Build and test binaries
        run: make test

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Build npm package
        run: npm ci && npm run build

      - name: Build phaser-example
        working-directory: phaser-example
        run: npm ci && npm run build
